server.port=8063

spring.datasource.url=jdbc:postgresql://localhost:5432/citizix_db
spring.datasource.username=citizix_user
spring.datasource.password=S3cret
spring.datasource.driver-class-name=org.postgresql.Driver